# Make folder and file for Streamlit secrets
import os
os.makedirs(".streamlit", exist_ok=True)

with open(".streamlit/secrets.toml", "w") as f:
    f.write('OPENAI_API_KEY = "sk-xxxxxxxxxxxxxxxxxxxx"')
